### ISSUE TITLE
Analyze which pre-commits hooks are necessary  

### ISSUE THREAD

**Issue by FedericoFuentesWeber** [ezeBalsamo/Digimon-Card-Game#72]
https://pre-commit.com/hooks.html

**Comment by ezeBalsamo** [comment]
To use:

- [x] reorder-python-imports
- [x] Black Formatter
- [x] bandit
- [x] ruff
- [x] isort
- [x] safety
- [x] radon/xenon

To not use:

- add-trailing-comma
- vulture
- flake8
- pylint
- autopep8
- yapf
- sonar

**Comment by ezeBalsamo** [comment]
Here I will be listing the ones we are going to use:
- black
- reorder-python-imports
